#!/bin/bash

function rdcon_single_timeslice() {
	# Note: This requires rdcon and all relevant .in files in your cwd
        fullpath=$1
        filename=$(basename ${fullpath})
        mkdir $filename
        cd $filename
        cp ../{rdcon,*.in} .
        cp $fullpath .
        sed -i "s/.*eq_filename.*/eq_filename=\"$filename\"/" equil.in
        ./rdcon
        cd ..
}

function rdcon_parallel() {
        export -f rdcon_single_timeslice
        ncores=$1
        files="${@:2}"
        ls $files | xargs -t -P $ncores -I {} bash -c 'rdcon_single_timeslice "{}"'
}

function delta_gw(){
	python3 -m rdcon_tools.delta_gw "$@"
}

function eqdsk_times() {
	# Pass in index.dat generated by createeqdsk on freia
	awk 'NR>2 {print $1}' $1 | sed 's/time=//'
}
