#!/bin/bash

load_rdcon_mod_csd() {
        module purge

        module load rhel8/default-icl
        module load intel-oneapi-tbb
        module load intel-oneapi-mkl
        module load fftw
        module load petsc/3.17-icl
        module load netcdf-fortran

	export FC=ifort
}

load_rdcon_mod_pita() {
        module purge

        module load intel-oneapi-tbb
        module load intel-oneapi-mkl
        module load intel-oneapi-compilers
        module load fftw
        module load petsc
        module load netcdf-fortran

	export FC=ifort
}


function rdcon_single_timeslice() {
	# Note: This requires rdcon and all relevant .in files in your cwd
        fullpath=$1
        filename=$(basename ${fullpath})
        mkdir $filename
        cp ../{rdcon,*.in} $filename
        cd $filename
	cp ../{rdcon,*.in} .
        cp $fullpath .
        sed -i "s/.*eq_filename.*/eq_filename=\"$filename\"/" equil.in
        ./rdcon
        cd ..
}

function rdcon_parallel() {
        export -f rdcon_single_timeslice
        ncores=$1
        files="${@:2}"
        ls $files | xargs -t -P $ncores -I {} bash -c 'rdcon_single_timeslice "{}"'
}

function delta_gw(){
	python3 -m rdcon_tools.delta_gw "$@"
}

function eqdsk_times() {
	# Pass in index.dat generated by createeqdsk on freia
	awk 'NR>2 {print $1}' $1 | sed 's/time=//'
}
