from scipy.interpolate import UnivariateSpline
import numpy as np
import pandas as pd
import sys

_name_time = r'%time'
_name_energies = r'E_{mag,01}'
_name_flux = r'psi_t'

def growth_rate(df: pd.DataFrame) -> np.array:
	"""
	Calculate growth rate of the perturbed flux from the magnetic energy live data
	generated by JOREK.
	"""
	times = df[r'%time']
	mag_energies = df[r'E_{mag,01}']

	W_spline = UnivariateSpline(times, mag_energies, s=0)
	dWdt_spline = W_spline.derivative()

	# Note factor of 0.5 since rate of change of flux is half the rate of change
	# of energy
	return 0.5*dWdt_spline(times)/W_spline(times)

if __name__=='__main__':
	from matplotlib import pyplot as plt

	filename = sys.argv[1]

	df = pd.read_csv(filename)

	growth_rates = growth_rate(df)

	print(growth_rates)

	fig, axs = plt.subplots(2)
	ax, ax2 = axs
	ax.plot(df[r'%time'][10:], growth_rates[10:])
	ax.set_xlabel("Time ($1/\omega_A$)")
	ax.set_ylabel("Growth rate")

	ax2.plot(df[r'%time'][10:], df[r'E_{mag,01}'][10:])

	plt.show()
